(()=>{
  const MODE_KEY='bedside_mode_settings_v1';
  const DEFAULTS={sleepStart:'23:00',wakeStart:'07:00',wakeEnd:'10:00',manual:'auto',studyGoal:'',showPending:3};
  const state={settings:{...DEFAULTS},mode:'general',tomorrowWeather:null};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const mins=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
  const nowMins=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()};
  const between=(n,start,end)=>start<=end?(n>=start&&n<end):(n>=start||n<end);
  function load(){try{state.settings={...DEFAULTS,...JSON.parse(localStorage.getItem(MODE_KEY)||'{}')}}catch{state.settings={...DEFAULTS}}}
  function save(){localStorage.setItem(MODE_KEY,JSON.stringify(state.settings))}
  function autoMode(){const n=nowMins(),s=mins(state.settings.sleepStart),w=mins(state.settings.wakeStart),e=mins(state.settings.wakeEnd);if(between(n,s,w))return'sleep';if(between(n,w,e))return'wake';return'general'}
  function currentMode(){return state.settings.manual==='auto'?autoMode():state.settings.manual}
  function injectStyles(){
    const style=document.createElement('style');style.id='modeSystemStyle';style.textContent=`
      #modeBadge{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;border:1px solid var(--line);background:var(--button);font-size:13px;font-weight:700;color:var(--muted);white-space:nowrap}
      #modeBadge .dot{width:7px;height:7px;border-radius:50%;background:#8e8e93}
      body.mode-sleep #modeBadge .dot{background:#7dd3fc} body.mode-wake #modeBadge .dot{background:#fbbf24}
      #sleepPanel{display:none;grid-column:1/3;min-height:0;grid-template-columns:minmax(0,1.35fr) minmax(280px,.8fr);gap:18px}
      .modeCard{border:1px solid rgba(255,255,255,.075);background:rgba(16,18,22,.68);border-radius:26px;padding:24px;backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px)}
      .modeEyebrow{font-size:13px;color:#777f8b;font-weight:750;letter-spacing:.08em;text-transform:uppercase;margin-bottom:12px}
      .modeMain{font-size:31px;line-height:1.18;font-weight:720;letter-spacing:-.8px}.modeSub{font-size:15px;color:#7f8792;margin-top:9px;line-height:1.55}.sleepWake{font-size:42px;font-weight:740;letter-spacing:-2px}.sleepList{display:grid;gap:9px;margin-top:4px}.sleepItem{font-size:16px;color:#b8bec7;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.055)}.sleepItem:last-child{border-bottom:0}
      #wakeStudy{display:none;margin-top:18px;padding-top:17px;border-top:1px solid var(--line)}#wakeStudy .goal{font-size:19px;line-height:1.45;margin-top:7px}.goalEmpty{color:var(--muted);font-size:15px}
      body.mode-sleep{background:#000!important;filter:none!important}body.mode-sleep .app{grid-template-rows:auto minmax(0,1fr);gap:18px;padding:24px 30px}body.mode-sleep .time{font-size:clamp(100px,11vw,154px);letter-spacing:-8px;color:#d7dce3}body.mode-sleep .date{color:#555d69}body.mode-sleep .weather{display:none}body.mode-sleep .card,body.mode-sleep .bottom{display:none!important}body.mode-sleep #sleepPanel{display:grid}body.mode-sleep .top{opacity:.72}body.mode-sleep .ib{background:rgba(255,255,255,.035);border-color:rgba(255,255,255,.06);color:#7a828d}
      body.mode-wake{filter:none!important;background:radial-gradient(circle at 80% 0%,#2a2313 0,transparent 32%),linear-gradient(180deg,#12100b,#08090b 58%)!important}body.mode-wake #wakeStudy{display:block}body.mode-wake .bottom{opacity:.72}body.mode-wake .card{border-color:rgba(255,255,255,.12)}
      #modeDialog{border:1px solid rgba(255,255,255,.1);border-radius:24px;background:#171b22;color:#f5f5f7;width:min(560px,90vw);padding:22px;box-shadow:0 30px 90px #000a}#modeDialog::backdrop{background:#000a;backdrop-filter:blur(8px)}
      .modeGrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.modeField{display:flex;flex-direction:column;gap:7px;margin:10px 0}.modeField label{font-size:13px;color:#9ba2ad}.modeField input,.modeField select{background:#0d1015;color:#f5f5f7;border:1px solid rgba(255,255,255,.09);border-radius:12px;padding:11px 12px;font:inherit}.modeWide{grid-column:1/3}.modeActions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.modeBtn{border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.07);color:#f5f5f7;border-radius:12px;padding:9px 13px;font:inherit}.modeHint{font-size:13px;color:#8f96a1;line-height:1.55;margin-top:8px}
      @media(max-width:900px){#sleepPanel{grid-column:1;grid-template-columns:1fr}.modeGrid{grid-template-columns:1fr}.modeWide{grid-column:1}}
    `;document.head.appendChild(style);
  }
  function setupUI(){
    const btn=document.getElementById('nightBtn');
    if(btn){btn.textContent='⚙︎';btn.setAttribute('aria-label','模式設定');btn.onclick=openSettings;btn.ondblclick=null;}
    const rt=$('.rt');if(rt&&!document.getElementById('modeBadge')){const badge=document.createElement('div');badge.id='modeBadge';badge.innerHTML='<span class="dot"></span><span id="modeBadgeText">一般</span>';rt.insertBefore(badge,btn||rt.firstChild)}
    const app=$('.app');if(app&&!document.getElementById('sleepPanel')){const p=document.createElement('section');p.id='sleepPanel';p.innerHTML=`
      <div class="modeCard"><div class="modeEyebrow">明日第一個行程</div><div class="modeMain" id="sleepNextTitle">明天沒有行程</div><div class="modeSub" id="sleepNextMeta">可以安心休息</div></div>
      <div class="modeCard"><div class="modeEyebrow">起床</div><div class="sleepWake" id="sleepWakeTime">07:00</div><div class="modeSub" id="sleepWeather">正在讀取明天天氣…</div></div>
      <div class="modeCard" style="grid-column:1/3"><div class="modeEyebrow">睡前提醒</div><div class="sleepList" id="sleepPending"></div></div>`;app.insertBefore(p,$('.bottom'))}
    const taskCard=document.querySelectorAll('.card')[1];if(taskCard&&!document.getElementById('wakeStudy')){const g=document.createElement('div');g.id='wakeStudy';g.innerHTML='<div class="dayTitle">今日讀書目標</div><div class="goal" id="studyGoalText"></div>';taskCard.appendChild(g)}
    if(!document.getElementById('modeDialog')){const d=document.createElement('dialog');d.id='modeDialog';d.innerHTML=`<h2 style="margin:0 0 6px">睡前 / 起床模式</h2><div class="modeHint">模式會依時間自動切換；也可以暫時手動指定模式。</div><div class="modeGrid"><div class="modeField"><label>睡前模式開始</label><input id="setSleepStart" type="time"></div><div class="modeField"><label>起床模式開始</label><input id="setWakeStart" type="time"></div><div class="modeField"><label>起床模式結束</label><input id="setWakeEnd" type="time"></div><div class="modeField"><label>目前模式</label><select id="setManual"><option value="auto">自動</option><option value="sleep">睡前</option><option value="wake">起床</option><option value="general">一般</option></select></div><div class="modeField modeWide"><label>今日讀書目標</label><input id="setStudyGoal" placeholder="例如：計組 Lecture 8 + 線代 2 小時"></div></div><div class="modeActions"><button class="modeBtn" id="modeCancel">取消</button><button class="modeBtn" id="modeSave">儲存</button></div>`;document.body.appendChild(d);d.querySelector('#modeCancel').onclick=()=>d.close();d.querySelector('#modeSave').onclick=saveSettings}
  }
  function openSettings(){const d=document.getElementById('modeDialog');if(!d)return;document.getElementById('setSleepStart').value=state.settings.sleepStart;document.getElementById('setWakeStart').value=state.settings.wakeStart;document.getElementById('setWakeEnd').value=state.settings.wakeEnd;document.getElementById('setManual').value=state.settings.manual;document.getElementById('setStudyGoal').value=state.settings.studyGoal||'';d.showModal()}
  function saveSettings(){const s=document.getElementById('setSleepStart').value,w=document.getElementById('setWakeStart').value,e=document.getElementById('setWakeEnd').value;if(!s||!w||!e)return;state.settings={...state.settings,sleepStart:s,wakeStart:w,wakeEnd:e,manual:document.getElementById('setManual').value,studyGoal:document.getElementById('setStudyGoal').value.trim()};save();document.getElementById('modeDialog').close();applyMode(true)}
  function getTomorrowFirst(){const box=document.getElementById('eventsTomorrow');if(!box)return null;const ev=box.querySelector('.event');if(!ev)return null;return{time:ev.querySelector('.et')?.textContent?.trim()||'',title:ev.querySelector('.title')?.textContent?.trim()||'',meta:ev.querySelector('.meta')?.textContent?.trim()||''}}
  function pendingTasks(){const out=[];document.querySelectorAll('#tasks .task').forEach(t=>{const cb=t.querySelector('input[type=checkbox]');const tx=t.querySelector('.taskText')?.textContent?.trim();if(tx&&(!cb||!cb.checked))out.push(tx)});return out.slice(0,state.settings.showPending||3)}
  function renderSleep(){const ev=getTomorrowFirst();const title=document.getElementById('sleepNextTitle'),meta=document.getElementById('sleepNextMeta');if(ev){title.textContent=(ev.time?ev.time+'  ':'')+ev.title;meta.textContent=ev.meta||'明天的第一個行程'}else{title.textContent='明天沒有行程';meta.textContent='可以安心休息'}document.getElementById('sleepWakeTime').textContent=state.settings.wakeStart;const ps=pendingTasks(),box=document.getElementById('sleepPending');box.innerHTML=ps.length?ps.map(x=>`<div class="sleepItem">${esc(x)}</div>`).join(''):'<div class="modeSub">沒有未完成的待辦</div>';renderTomorrowWeather()}
  function renderWake(){const g=document.getElementById('studyGoalText');if(g)g.innerHTML=state.settings.studyGoal?esc(state.settings.studyGoal):'<span class="goalEmpty">尚未設定，點右上角 ⚙︎ 新增今日讀書目標</span>'}
  function applyMode(force=false){const m=currentMode();if(!force&&m===state.mode)return;state.mode=m;document.body.classList.remove('night','mode-sleep','mode-wake','mode-general');document.body.classList.add('mode-'+m);localStorage.setItem('manualNight','0');const label={sleep:'睡前',wake:'起床',general:'一般'}[m];const b=document.getElementById('modeBadgeText');if(b)b.textContent=label;if(m==='sleep')renderSleep();if(m==='wake')renderWake()}
  async function fetchTomorrowWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=25.033&longitude=121.5654&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FTaipei&forecast_days=2',{cache:'no-store'}),j=await r.json();state.tomorrowWeather={code:j.daily.weather_code?.[1],max:j.daily.temperature_2m_max?.[1],min:j.daily.temperature_2m_min?.[1],rain:j.daily.precipitation_probability_max?.[1]};renderTomorrowWeather()}catch{}}
  function weatherName(c){return c===0?'晴朗':c<=3?'多雲':c<=48?'有霧':c<=67?'有雨':c<=77?'降雪':c<=82?'陣雨':'雷雨'}
  function renderTomorrowWeather(){const el=document.getElementById('sleepWeather');if(!el)return;if(!state.tomorrowWeather){el.textContent='正在讀取明天天氣…';return}const w=state.tomorrowWeather;el.textContent=`明天 ${weatherName(w.code)} · ${Math.round(w.min)}–${Math.round(w.max)}° · 降雨 ${Math.round(w.rain||0)}%`}
  function observeDynamic(){const obs=new MutationObserver(()=>{if(state.mode==='sleep')renderSleep();if(state.mode==='wake')renderWake()});['eventsTomorrow','tasks'].forEach(id=>{const n=document.getElementById(id);if(n)obs.observe(n,{childList:true,subtree:true,attributes:true})})}
  load();injectStyles();setupUI();applyMode(true);fetchTomorrowWeather();observeDynamic();setInterval(()=>applyMode(false),30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){applyMode(true);fetchTomorrowWeather()}});
})();
